# Generated by Django 4.2.11 on 2024-03-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0003_rename_order_date_order_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',)},
        ),
    ]
