# Generated by Django 4.2.11 on 2024-03-05 17:23

import bookstore_api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore_api', '0004_alter_book_options_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[bookstore_api.validators.validate_positive_non_zero_value]),
        ),
    ]
